table d_DE-PARA-SERVIÇO
	lineageTag: b1ff350e-7ad2-4095-bfb6-7051d94ccf4d

	column 'DESC. TIPO SERV.'
		dataType: string
		lineageTag: 0373673c-c4f9-4f20-bfcd-8fe8d3e8ae7c
		summarizeBy: none
		sourceColumn: DESC. TIPO SERV.

		annotation SummarizationSetBy = Automatic

	column CATEGORIA
		dataType: string
		lineageTag: 0b733338-e04b-4f1f-9045-c9619e6d4677
		summarizeBy: none
		sourceColumn: CATEGORIA

		annotation SummarizationSetBy = Automatic

	partition d_DE-PARA-SERVIÇO = m
		mode: import
		queryGroup: 'DE PARA'
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(#"Pasta Raiz" & "\DE PARA PXX.xlsx"), null, true),
				    #"DE PARA SERVIÇO_Sheet" = Fonte{[Item="DE PARA SERVIÇO",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"DE PARA SERVIÇO_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DESC. TIPO SERV.", type text}, {"CATEGORIA", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

