table f_SaldoEstoque
	lineageTag: 7b953ee0-509f-4059-84a1-d33803de4dd8

	column 'Tipo Saldo'
		dataType: string
		lineageTag: 57fc2c7f-b4bc-4293-b3b2-0da737980c5e
		summarizeBy: none
		sourceColumn: Tipo Saldo

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: f856db86-5097-4f38-a381-3b0ee5c898d6
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column Codmat
		dataType: string
		lineageTag: 305d53ba-d2f2-48f5-b9e7-9774939c1aec
		summarizeBy: none
		sourceColumn: Codmat

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 5744efa1-b77d-4f20-bedd-2decb977ce37
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	column Unid
		dataType: string
		lineageTag: f0d235ca-a225-4443-8ece-a717a4e1d00f
		summarizeBy: none
		sourceColumn: Unid

		annotation SummarizationSetBy = Automatic

	column 'Saldo em Estoque'
		dataType: int64
		formatString: 0
		lineageTag: 1e661df8-d80b-4712-bf65-64d38befb2fa
		summarizeBy: sum
		sourceColumn: Saldo em Estoque

		annotation SummarizationSetBy = Automatic

	column 'Prog. RM'
		dataType: int64
		formatString: 0
		lineageTag: 52c711bb-8a20-4546-8dc7-c8f40c9e7c05
		summarizeBy: sum
		sourceColumn: Prog. RM

		annotation SummarizationSetBy = Automatic

	column 'Prog. TM'
		dataType: int64
		formatString: 0
		lineageTag: 3cc70c9e-06e4-46f3-bee3-4fc3af4805af
		summarizeBy: sum
		sourceColumn: Prog. TM

		annotation SummarizationSetBy = Automatic

	column 'Saldo Disponível'
		dataType: int64
		formatString: 0
		lineageTag: 37a0fad9-21c1-4259-98ef-a687a14ab6bf
		summarizeBy: sum
		sourceColumn: Saldo Disponível

		annotation SummarizationSetBy = Automatic

	column CATEGORIA
		dataType: string
		lineageTag: 8b30e4ca-d94e-442e-a3c0-a9095ce021fd
		summarizeBy: none
		sourceColumn: CATEGORIA

		annotation SummarizationSetBy = Automatic

	column CONDIÇÃO
		dataType: string
		lineageTag: 06e47def-2585-43d4-a5b5-76b0a08a9da2
		summarizeBy: none
		sourceColumn: CONDIÇÃO

		annotation SummarizationSetBy = Automatic

	column 'Cód. Mat. Auxiliar'
		dataType: string
		lineageTag: 672bc301-0a8c-4ec7-81b1-0fe4934d6edb
		summarizeBy: none
		sourceColumn: Cód. Mat. Auxiliar

		annotation SummarizationSetBy = Automatic

	column 'Cód. Cpl. Auxiliar'
		dataType: string
		lineageTag: a1b84d16-0679-4a12-8287-f986961275d0
		summarizeBy: none
		sourceColumn: Cód. Cpl. Auxiliar

		annotation SummarizationSetBy = Automatic

	partition f_SaldoEstoque = m
		mode: import
		queryGroup: Estoque
		source = ```
				let
				    Fonte = Excel.Workbook(File.Contents(#"Pasta Raiz" & "\saldo\Localizar Saldo de Material em Estoque.xlsx"), null, true),
				    SINAPSE_Sheet = Fonte{[Item="SINAPSE",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(SINAPSE_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",1),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Tipo Saldo", type text}, {"Grupo", type text}, {"Codmat", type text}, {"Descrição", type text}, {"Descrição Auxiliar", type text}, {"Unid", type text}, {"Codcpl", type text}, {"Saldo em Estoque", Int64.Type}, {"Prog. RM", Int64.Type}, {"Prog. TM", Int64.Type}, {"Valor", type number}, {"Cod. Grupo Material", Int64.Type}, {"Grupo de Material", type text}, {"Saldo Disponível", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"Descrição Auxiliar", "Codcpl", "Valor", "Cod. Grupo Material", "Grupo de Material"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Removidas", {"Descrição"}, #"d_DE-PARA-TECNOLOGIA", {"EQUIPAMENTO"}, "d_DE-PARA-TECNOLOGIA", JoinKind.LeftOuter),
				    #"d_DE-PARA-TECNOLOGIA Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "d_DE-PARA-TECNOLOGIA", {"CATEGORIA"}, {"d_DE-PARA-TECNOLOGIA.CATEGORIA"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"d_DE-PARA-TECNOLOGIA Expandido",null,"NÃO MAPEADO",Replacer.ReplaceValue,{"d_DE-PARA-TECNOLOGIA.CATEGORIA"}),
				    Condição = Table.AddColumn(#"Valor Substituído", "CONDIÇÃO", each 
				    let 
				        Cod = Text.Upper(Text.From([Descrição])) 
				    in
				        if Text.Contains(Cod, "DEF-") or Text.Contains(Cod, "DET-") then "DEFEITO"
				        else if Text.Contains(Cod, "RET-") then "RETIRADO"
				        else if Text.Contains(Cod, "REAP-") /*or Text.Contains(Cod, "REA-") */ then "REAPROVEITADO"
				        else if Text.Contains(Cod, "SUC-") then "DESUSO"
				        else if [Descrição] <> null and [Descrição] <> "" then "NOVO"
				        else "VAZIO"
				    ),
				    #"Colunas Renomeadas" = Table.RenameColumns(Condição,{{"d_DE-PARA-TECNOLOGIA.CATEGORIA", "CATEGORIA"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"CONDIÇÃO", type text}})
				in
				    #"Tipo Alterado2"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

