table f_Solicitacoes
	lineageTag: 88732d1a-3399-44db-b887-82baf55eff4c

	column Contrato
		dataType: string
		lineageTag: 6d510512-9bb7-46b5-a54a-03e7b3ea1e55
		summarizeBy: none
		sourceColumn: Contrato

		annotation SummarizationSetBy = Automatic

	column Projeto
		dataType: string
		lineageTag: 9e19eaae-607c-43ef-aa75-57c5be4a583f
		summarizeBy: none
		sourceColumn: Projeto

		annotation SummarizationSetBy = Automatic

	column 'Nº. Ordem Serviço'
		dataType: string
		lineageTag: 99580169-5153-46d7-b88b-bcc16e0c35c4
		summarizeBy: none
		sourceColumn: Nº. Ordem Serviço

		annotation SummarizationSetBy = Automatic

	column 'Matrícula do Técnico'
		dataType: string
		lineageTag: c6230eb3-3f55-4848-ac79-54347214bc69
		summarizeBy: none
		sourceColumn: Matrícula do Técnico

		annotation SummarizationSetBy = Automatic

	column 'Identificação do Cliente'
		dataType: string
		lineageTag: 0e91725e-7bc3-4346-88a2-4f566c658e3d
		summarizeBy: none
		sourceColumn: Identificação do Cliente

		annotation SummarizationSetBy = Automatic

	column Responsável
		dataType: string
		lineageTag: fa7498dc-4f6a-471f-a50b-fb26168ea077
		summarizeBy: none
		sourceColumn: Responsável

		annotation SummarizationSetBy = Automatic

	column 'Nº Cliente'
		dataType: string
		lineageTag: 75192850-403a-47b7-91ae-8f9182bcd0b4
		summarizeBy: none
		sourceColumn: Nº Cliente

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1f303e23-feb9-4b44-b31f-832cd529a828
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Serviço'
		dataType: string
		lineageTag: c234300d-081f-40eb-9f1b-0236bb182944
		summarizeBy: none
		sourceColumn: Tipo de Serviço

		annotation SummarizationSetBy = Automatic

	column 'Grupo Área'
		dataType: string
		lineageTag: d6845f70-3ac6-4eea-815f-2bc3d0b6416c
		summarizeBy: none
		sourceColumn: Grupo Área

		annotation SummarizationSetBy = Automatic

	column 'Data/Hora Criação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 725f391d-671a-4316-ac96-21ddd526aa0a
		summarizeBy: none
		sourceColumn: Data/Hora Criação

		variation Variation
			isDefault
			relationship: ec34e42d-536f-4fd8-b884-be86fd2a3f59
			defaultHierarchy: LocalDateTable_44418a52-2974-4f56-a642-9a2ceaf8ff76.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data/Hora Encerramento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0ca9fd3c-dbf2-434c-9394-38fc54b90f75
		summarizeBy: none
		sourceColumn: Data/Hora Encerramento

		variation Variation
			isDefault
			relationship: bc8c0a69-8cb6-417a-86ac-653567b251ff
			defaultHierarchy: LocalDateTable_3b2d7d9d-c9e3-4ce3-aca9-376304c76b6f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Natureza
		dataType: string
		lineageTag: eaf22bed-cb9e-4a78-bf37-af7f09619f0b
		summarizeBy: none
		sourceColumn: Natureza

		annotation SummarizationSetBy = Automatic

	column Plano/Produto
		dataType: string
		lineageTag: 71530ea7-d61a-42f3-9e93-84d7a544b633
		summarizeBy: none
		sourceColumn: Plano/Produto

		annotation SummarizationSetBy = Automatic

	column 'Velocidade do Plano'
		dataType: int64
		formatString: 0
		lineageTag: 9f45924d-1a47-40c9-8118-719dabd5aafd
		summarizeBy: sum
		sourceColumn: Velocidade do Plano

		annotation SummarizationSetBy = Automatic

	column Roteadores
		dataType: string
		lineageTag: 05539753-3a5b-4654-b7c6-56478d938982
		summarizeBy: none
		sourceColumn: Roteadores

		annotation SummarizationSetBy = Automatic

	column 'Velocidade Agrupada' =
			
			
			VAR velocidade = f_Solicitacoes[Velocidade do Plano]
			RETURN
			SWITCH(
			    TRUE(),
			    velocidade >= 1 && velocidade <= 20, "001MB - 020MB",
			    velocidade > 20 && velocidade <= 50, "021MB - 050MB",
			    velocidade > 50 && velocidade <= 100, "051MB - 100MB",
			    velocidade > 100 && velocidade <= 300, "101MB - 300MB",
			    velocidade > 300 && velocidade <= 600, "301MB - 600MB",
			    velocidade > 600 && velocidade <= 1000, "601MB - 1GB",
			    velocidade > 1000 && velocidade <= 2000, "2GB+",
			    "NÃO IDENTIFICADO"
			)
		lineageTag: bf50d926-785e-43af-86c0-223273df6764
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Data Baixa OS'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 427e93a3-f68e-484c-b063-d0244b6b8aa8
		summarizeBy: none
		sourceColumn: Data Baixa OS

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Material Aplicado OS' =
			VAR OSAtual = 'f_Solicitacoes'[Nº. Ordem Serviço]
			VAR Materiais =
			    SELECTCOLUMNS(
			        FILTER(
			            'f_MateriaisAplicados',
			            'f_MateriaisAplicados'[OS] = OSAtual
			                && UPPER(TRIM('f_MateriaisAplicados'[Serializado?])) = "SIM"
			                && NOT ISBLANK('f_MateriaisAplicados'[Material])
			        ),
			        "Material", 'f_MateriaisAplicados'[Material]
			    )
			RETURN
			    IF(
			        ISBLANK(OSAtual),
			        BLANK(),
			        CONCATENATEX(Materiais, [Material], ", ", [Material], ASC)
			    )
		dataType: string
		lineageTag: 57b08f56-72e2-4cfe-9af3-dbe5127fb717
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nº. Serie OS' =
			VAR OSAtual = 'f_Solicitacoes'[Nº. Ordem Serviço]
			VAR Seriais =
			    DISTINCT(
			        SELECTCOLUMNS(
			            FILTER(
			                'f_MateriaisAplicados',
			                'f_MateriaisAplicados'[OS] = OSAtual
			                    && UPPER(TRIM('f_MateriaisAplicados'[Serializado?])) = "SIM"
			                    && NOT ISBLANK('f_MateriaisAplicados'[N° Serie])
			            ),
			            "Serie", 'f_MateriaisAplicados'[N° Serie]
			        )
			    )
			RETURN
			    IF(
			        ISBLANK(OSAtual),
			        BLANK(),
			        CONCATENATEX(Seriais, [Serie], ", ", [Serie], ASC)
			    )
		dataType: string
		lineageTag: 604089db-00fa-4545-8f42-e88d5bfbd018
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Qtd. Aplic. OS' =
			VAR OSAtual = 'f_Solicitacoes'[Nº. Ordem Serviço]
			RETURN
			    IF(
			        ISBLANK(OSAtual),
			        BLANK(),
			        CALCULATE(
			            SUM('f_MateriaisAplicados'[Qtde. Aplic.]),
			            'f_MateriaisAplicados'[OS] = OSAtual,
			            UPPER(TRIM('f_MateriaisAplicados'[Serializado?])) = "SIM"
			        )
			    )
		dataType: double
		formatString: #,0.##
		lineageTag: a4e1d81b-6175-44fe-8315-acb1d7b1bf83
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Plano' = ```
			
			/*
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "MESH") || 'f_Solicitacoes'[Roteadores] IN {"2R", "3R"},
			        "WIFI 6 MESH " & COALESCE('f_Solicitacoes'[Roteadores], "2R"),
			    CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "CAMBIUM") || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Radio") || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Rádio"),
			        "RÁDIO",
			    'f_Solicitacoes'[Velocidade do Plano] > 300 || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "WIFI 6") || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "WIFI6"),
			        "WIFI 6",
			    ('f_Solicitacoes'[Velocidade do Plano] >= 1 && 'f_Solicitacoes'[Velocidade do Plano] <= 300) || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Me Aproxxima"),
			        "WIFI 5",
			    "SEM INFORMAÇÃO PLANO"
			)*/
			
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "CAMBIUM") || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Radio") || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Rádio"), "RÁDIO",
			    CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "MESH") 
			        || 'f_Solicitacoes'[Roteadores] IN {"2R", "3R"} 
			        || 'f_Solicitacoes'[Velocidade do Plano] > 300 
			        || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "WIFI 6") 
			        || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "WIFI6"), "WIFI 6",
			    ('f_Solicitacoes'[Velocidade do Plano] >= 1 && 'f_Solicitacoes'[Velocidade do Plano] <= 300) || CONTAINSSTRING('f_Solicitacoes'[Plano/Produto], "Me Aproxxima"),
			        "WIFI 5",
			    "SEM INFORMAÇÃO PLANO"
			)
			```
		dataType: string
		lineageTag: 427cffcd-be71-459f-bc28-b87fca03c7d2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'CATEGORIA APLICADA OS' =
			VAR OSAtual = 'f_Solicitacoes'[Nº. Ordem Serviço]
			VAR MateriaisAplicados =
			    FILTER(
			        'f_MateriaisAplicados',
			        'f_MateriaisAplicados'[OS] = OSAtual
			            && UPPER(TRIM('f_MateriaisAplicados'[Serializado?])) = "SIM"
			            && NOT ISBLANK('f_MateriaisAplicados'[Material])
			    )
			VAR CategoriasBase =
			    ADDCOLUMNS(
			        MateriaisAplicados,
			        "Categoria",
			            LOOKUPVALUE(
			                'd_DE-PARA-TECNOLOGIA'[CATEGORIA],
			                'd_DE-PARA-TECNOLOGIA'[EQUIPAMENTO],
			                'f_MateriaisAplicados'[Material]
			            )
			    )
			VAR CategoriasValidas =
			    FILTER(CategoriasBase, NOT ISBLANK([Categoria]))
			VAR CategoriasUnicas =
			    DISTINCT(
			        SELECTCOLUMNS(
			            CategoriasValidas,
			            "CategoriaResumo", [Categoria]
			        )
			    )
			VAR CategoriasComQtde =
			    ADDCOLUMNS(
			        CategoriasUnicas,
			        "Qtde",
			            VAR CategoriaAtual = [CategoriaResumo]
			            RETURN
			                COUNTROWS(
			                    FILTER(
			                        CategoriasValidas,
			                        [Categoria] = CategoriaAtual
			                    )
			                )
			    )
			RETURN
			    IF(
			        ISBLANK(OSAtual),
			        BLANK(),
			        IF(
			            COUNTROWS(MateriaisAplicados) = 0,
			            BLANK(),
			            IF(
			                COUNTROWS(CategoriasValidas) = 0,
			                "NÃO MAPEADO",
			                CONCATENATEX(
			                    CategoriasComQtde,
			                    [CategoriaResumo] & " (" & [Qtde] & ")",
			                    ", ",
			                    [CategoriaResumo],
			                    ASC
			                )
			            )
			        )
			    )
		dataType: string
		lineageTag: 7be0426a-73c8-4a72-869c-b6144f92fcec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'CONFORMIDADE APLICAÇÃO' = ```
			VAR CategoriaAplicadaOS = TRIM(COALESCE('f_Solicitacoes'[CATEGORIA APLICADA OS], ""))
			VAR TipoPlano = UPPER(TRIM(COALESCE('f_Solicitacoes'[Tipo de Plano], "")))
			VAR Velocidade = 'f_Solicitacoes'[Velocidade do Plano]
			VAR OSAtual = 'f_Solicitacoes'[Nº. Ordem Serviço]
			VAR MateriaisOS =
			    FILTER(
			        'f_MateriaisAplicados',
			        'f_MateriaisAplicados'[OS] = OSAtual
			            && UPPER(TRIM('f_MateriaisAplicados'[Serializado?])) = "SIM"
			            && NOT ISBLANK('f_MateriaisAplicados'[Material])
			    )
			VAR MateriaisComCategoria =
			    ADDCOLUMNS(
			        MateriaisOS,
			        "Categoria",
			            LOOKUPVALUE(
			                'd_DE-PARA-TECNOLOGIA'[CATEGORIA],
			                'd_DE-PARA-TECNOLOGIA'[EQUIPAMENTO],
			                'f_MateriaisAplicados'[Material]
			            )
			    )
			VAR MateriaisMapeados =
			    FILTER(
			        MateriaisComCategoria,
			        NOT ISBLANK([Categoria])
			    )
			VAR TemMateriais = COUNTROWS(MateriaisOS) > 0
			VAR TemMaterialNaoMapeado = COUNTROWS(MateriaisComCategoria) <> COUNTROWS(MateriaisMapeados)
			VAR QtdeONTWifi6 = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "ONT WIFI 6"))
			VAR QtdeRoteadorWifi6 = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "ROTEADOR WIFI 6"))
			VAR QtdeRadio = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "RADIO"))
			VAR QtdeONT5G = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "ONT 5G"))
			VAR QtdeRoteador5G = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "ROTEADOR 5G" || [Categoria] = "ONU + ROT 5G"))
			VAR QtdeONU = COUNTROWS(FILTER(MateriaisMapeados, [Categoria] = "ONU"))
			VAR MESH3RConforme = --3R
			    NOT TemMaterialNaoMapeado
			        && (
			            (QtdeONTWifi6 = 1 && QtdeONU = 0 && QtdeRoteadorWifi6 = 2) || 
			            (QtdeONTWifi6 = 0 && QtdeONU = 1 && QtdeRoteadorWifi6 = 3)
			        )
			        && QtdeRadio = 0
			        && QtdeONT5G = 0
			        && QtdeRoteador5G = 0
			VAR MESH2RConforme = --2R
			    NOT TemMaterialNaoMapeado
			        && (
			            (QtdeONTWifi6 = 1 && QtdeONU = 0  && QtdeRoteadorWifi6 = 1) || 
			            (QtdeONTWifi6 = 0 && QtdeONU = 1 && QtdeRoteadorWifi6 = 2)
			        )
			        && QtdeRadio = 0
			        && QtdeONT5G = 0
			        && QtdeRoteador5G = 0
			VAR MESHConforme = --1R
			    NOT TemMaterialNaoMapeado
			        && (
			            (QtdeONTWifi6 = 1 && QtdeONU = 0  && QtdeRoteadorWifi6 = 1) || 
			            (QtdeONTWifi6 = 0 && QtdeONU = 1 && QtdeRoteadorWifi6 = 2)
			        )
			        && QtdeRadio = 0
			        && QtdeONT5G = 0
			        && QtdeRoteador5G = 0
			VAR Wifi6Conforme =
			    NOT TemMaterialNaoMapeado
			        && (
			            (QtdeONTWifi6 = 1 && QtdeONU = 0 && QtdeRoteadorWifi6 = 0) ||
			            (QtdeONTWifi6 = 0 && QtdeONU = 1 && QtdeRoteadorWifi6 = 1)
			        )
			        && QtdeRadio = 0
			        && QtdeONT5G = 0
			        && QtdeRoteador5G = 0
			VAR Wifi5Conforme =
			    NOT TemMaterialNaoMapeado
			        && (
			            (QtdeONT5G = 1 && QtdeONU = 0 && QtdeRoteador5G = 0) ||
			            (QtdeONT5G = 0 && QtdeONU = 1 && QtdeRoteador5G = 1)
			        )
			        && QtdeONTWifi6 = 0
			        && QtdeRoteadorWifi6 = 0
			        && QtdeRadio = 0
			VAR RadioConforme =
			    NOT TemMaterialNaoMapeado
			        && QtdeRadio = 1
			        && QtdeONTWifi6 = 0
			        && QtdeRoteadorWifi6 = 0
			        && QtdeONT5G = 0
			        && QtdeRoteador5G = 0
			        && QtdeONU = 0
			VAR SemInformacao =
			    (TipoPlano = "" || TipoPlano = "SEM INFORMAÇÃO PLANO")
			        && ISBLANK(Velocidade)
			RETURN
			    IF(
			        CategoriaAplicadaOS = "",
			        BLANK(),
			        IF(
			            SemInformacao,
			            "SEM INFORMAÇÃO",
			            IF(
			                NOT TemMateriais,
			                "NÃO CONFORME",
			                SWITCH(
			                    TRUE(),
			                    TipoPlano = "WIFI 6 MESH 3R", IF(MESH3RConforme, "CONFORME", "NÃO CONFORME"),
			                    TipoPlano = "WIFI 6 MESH 2R", IF(MESH2RConforme, "CONFORME", "NÃO CONFORME"),
			                    CONTAINSSTRING(TipoPlano, "WIFI 6 MESH"), IF(MESHConforme, "CONFORME", "NÃO CONFORME"),
			                    TipoPlano = "WIFI 6", IF(Wifi6Conforme, "CONFORME", "NÃO CONFORME"),
			                    TipoPlano = "WIFI 5", IF(Wifi5Conforme, "CONFORME", "NÃO CONFORME"),
			                    TipoPlano = "RÁDIO", IF(RadioConforme, "CONFORME", "NÃO CONFORME"),
			                    "NÃO CONFORME"
			                )
			            )
			        )
			    )
			```
		dataType: string
		lineageTag: a018c2cb-6cb2-4973-ac6b-cf2335ca3897
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Categoria Aplicada Agrupada' =
			
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "ONT WIFI 6") || CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "ROTEADOR WIFI 6"), "WIFI 6",
			    CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "ONT 5G") || CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "ROTEADOR 5G"), "WIFI 5",
			    CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "ONU"), "BRIDGE",
			    CONTAINSSTRING(f_Solicitacoes[CATEGORIA APLICADA OS], "RADIO"), "RADIO",
			    "Tecnologia Não Mapeada"
			)
		lineageTag: 08710e9e-2e82-4770-9223-6d2ccc4fbb9e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Serializado? =
			
			
			IF(f_Solicitacoes[Nº. Serie OS] <> "-" && f_Solicitacoes[Nº. Serie OS] <> "" && f_Solicitacoes[Nº. Serie OS] <> " " && NOT ISBLANK(f_Solicitacoes[Nº. Serie OS]), "SIM", "NÃO")
		lineageTag: 496434ef-5f0e-4a3c-bb5a-d90b8ac10132
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition f_Solicitacoes = m
		mode: import
		queryGroup: 'Transformar Arquivo de Solicitações'
		source =
				let
				  Origem = Folder.Files("C:\Users\proxx\OneDrive\Área de Trabalho\PXX\Estoque\Solicitações"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Origem, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (6)", each #"Transformar Arquivo (6)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (6)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (6)", Table.ColumnNames(#"Transformar Arquivo (6)"(#"Arquivo de Amostra (6)"))),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna de Tabela Expandida1",{"Nome da Origem", "CPF/CNPJ do Cliente", "N° da Venda", "Nº Atendimento", "Responsabilidade", "Pontos Previstos", "Pontos Realizados", "SLA", "Tipo de Imóvel", "Supervisor", "Área", "Localidade", "Cliente", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "UF", "País", "Telefone Principal", "Telefone Celular", "Usuário de Abertura OS", "Subtipo de Serviço", "Data/Hora Abertura Original", "Usuário do Agendamento", "Data/Hora do Agendamento", "Deslocamento", "Início Atendimento", "Final Atendimento", "Data/Hora Deslocamento", "Data/Hora Início do Atendimento", "Data/Hora Pausa Atendimento", "Data/Hora Reinício Atendimento", "Data/Hora Fim do Atendimento", "Status Auditoria", "Descrição do Encerramento", "Data/Hora Venc. O.S.", "Atendimento Finalizado", "Usuário do Encerramento", "Categoria do Cliente", "Monitor", "Período", "Motivo Paralisação", "Latitude/Longitude", "Quantidade Reabertura", "WO", "Tem Os Digital ?", "Departamento", "Tipo Prioridade", "Status da Cobrança", "Segmento", "TECNICO AUXILIAR", "Observação do Técnico", "Observação"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Contrato", type text}, {"Projeto", type text}, {"Nº. Ordem Serviço", type text}, {"Matrícula do Técnico", type text}, {"Identificação do Cliente", type text}, {"Responsável", type text}, {"Nº Cliente", type text}, {"Status", type text}, {"Tipo de Serviço", type text}, {"Grupo Área", type text}, {"Data/Hora Criação", type datetime}, {"Data/Hora Encerramento", type datetime}, {"Natureza", type text}, {"Plano/Produto", type text}, {"Velocidade do Plano", Int64.Type}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Tipo Alterado", "Data/Hora Encerramento", "Data/Hora Encerramento - Copiar"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Duplicada",{{"Data/Hora Encerramento - Copiar", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Data/Hora Encerramento - Copiar", "Data Baixa OS"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

